version: '3.8'

services:
  ai-backend:
    build: .
    container_name: ai-backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/workspace/app  # 코드 실시간 반영
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia  # GPU 사용

